### ISSUE TITLE
Staticman pull requests failing

### ISSUE THREAD

**Issue by ryanckim** [CVSSP/listen-sisec-mus-18-subjective-evaluation#3]
After clicking the submit button at the end, an error message pops up and the pull request is not made. The new branch is still being committed and pushed so the data is still available.

**Comment by deeuu** [comment]
Might be related to this [staticman issue](https://github.com/eduardoboucas/staticman/issues/217)

What response/error do you get?

**Comment by ryanckim** [comment]
Yeah, that’s the message. So that must be new. I had that on Friday which made me think there was a bug but then I found the branches are being created anyway so it’s ok to run the test at least.

Cheers,
Ryan
